<?php if (!defined('KRIS_EDITOR')) { http_response_code(404); exit; }
$list = array_values(array_filter($data, fn($item) => $item['name'] === $group)); ?>
<div class="container">
    <header class="page-heading"><div><p class="eyebrow">RACCOLTA</p><h1><?= h(editorLabel($group)) ?></h1><p>Apri un contenuto per modificarlo, oppure aggiungine uno nuovo.</p></div><div class="actions"><a class="btn btn-white" href="?action=structure&amp;group=<?= urlencode($group) ?>"><?= uiIcon('structure') ?>Struttura</a><?php if (!empty($models[$group])): ?><form method="POST"><input type="hidden" name="group" value="<?= h($group) ?>"><button class="btn btn-primary" name="create_instance"><?= uiIcon('plus') ?>Nuovo contenuto</button></form><?php endif; ?></div></header>
    <?php if (empty($models[$group])): ?><div class="empty-state"><h2>Prima definiamo cosa raccontare.</h2><p>Questa raccolta non ha ancora campi. Configura il modello prima di aggiungere contenuti.</p><a class="btn btn-primary" href="?action=structure&amp;group=<?= urlencode($group) ?>">Configura i campi</a></div>
    <?php elseif (!$list): ?><div class="empty-state"><h2>Il primo contenuto, quando vuoi.</h2><p>Usa “Nuovo contenuto” per iniziare a compilare la raccolta.</p></div>
    <?php else: ?>
    <div class="toolbar"><label class="search-box"><?= uiIcon('search') ?><input type="search" data-filter="contents" placeholder="Cerca un contenuto..." aria-label="Cerca un contenuto"></label><span class="badge"><?= count($list) ?> contenuti</span></div>
    <div class="card table-card"><table class="dnd-table content-table" data-dnd-scope="root" data-filter-list="contents" data-reorder-form="reorder_root_form"><thead><tr><th>Contenuto</th><th class="order-column">Ordine</th><th><span class="sr-only">Azioni</span></th></tr></thead><tbody>
    <?php foreach ($list as $index => $item): $title = editorTitle($item); ?>
    <tr draggable="true" data-id="<?= (int) $item['id'] ?>" data-search="<?= h($title) ?>"><td><div class="content-label"><span class="collection-icon"><?= uiIcon('content') ?></span><div><a class="content-title" href="?action=edit&amp;group=<?= urlencode($group) ?>&amp;id=<?= (int) $item['id'] ?>"><?= h($title) ?></a><small>Contenuto #<?= (int) $item['id'] ?></small></div></div></td><td><div class="order-actions"><button type="button" class="icon-button" data-move="-1" aria-label="Sposta <?= h($title) ?> in alto" <?= $index === 0 ? 'disabled' : '' ?>><?= uiIcon('up') ?></button><button type="button" class="icon-button" data-move="1" aria-label="Sposta <?= h($title) ?> in basso" <?= $index === count($list)-1 ? 'disabled' : '' ?>><?= uiIcon('down') ?></button></div></td><td><div class="row-actions"><a class="btn btn-white" href="?action=edit&amp;group=<?= urlencode($group) ?>&amp;id=<?= (int) $item['id'] ?>">Modifica</a><form method="POST" data-confirm-title="Eliminare questo contenuto?" data-confirm="&ldquo;<?= h($title) ?>&rdquo; e i suoi elementi annidati verranno eliminati. Non puoi annullare questa operazione dall’editor." data-confirm-label="Elimina contenuto"><input type="hidden" name="delete_instance" value="1"><input type="hidden" name="group" value="<?= h($group) ?>"><input type="hidden" name="id" value="<?= (int) $item['id'] ?>"><button class="icon-button danger" aria-label="Elimina <?= h($title) ?>"><?= uiIcon('trash') ?></button></form></div></td></tr>
    <?php endforeach; ?></tbody></table></div><div class="empty-state" data-filter-empty="contents" hidden><h2>Nessun contenuto trovato.</h2><p>Prova un altro nome o svuota la ricerca.</p></div><p class="hint">L’ordine viene salvato subito. Puoi usare le frecce oppure trascinare le righe.</p>
    <form method="POST" action="<?= h($BASE) ?>" id="reorder_root_form" hidden><input type="hidden" name="reorder_root" value="1"><input type="hidden" name="group" value="<?= h($group) ?>"><input type="hidden" name="order" value=""></form>
    <?php endif; ?>
</div>
