const fs = require('fs');
const {pathToFileURL} = require('url');
const [,,port,folder] = process.argv;
async function main(){
 const tabs=await (await fetch(`http://127.0.0.1:${port}/json`)).json();
 const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let seq=0;const waiting=new Map();const exceptions=[];
 ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=waiting.get(m.id);waiting.delete(m.id);if(m.error)p.reject(m.error);else p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails.text+': '+m.params.exceptionDetails.exception?.description);});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 const results=[];const assert=(name,ok)=>{results.push({name,ok});if(!ok)throw new Error('FAILED: '+name);};
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const input=(selector,value)=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
 await call('Page.enable');await call('Runtime.enable');
 await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
 await call('Page.navigate',{url:pathToFileURL(folder+'/index.html').href});
 for(let i=0;i<60;i++){if(await evaluate(`document.querySelector('#page-title')!==null`))break;await new Promise(r=>setTimeout(r,100));}
 assert('Initial edit rendered',await evaluate(`document.querySelector('#page-title').value==='Le idee prendono forma.'`));
 let screenshot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(folder+'/anteprima-desktop.png',Buffer.from(screenshot.data,'base64'));
 await input('#page-title','Nuovo titolo di prova');
 assert('Dirty state and live preview',await evaluate(`dirty() && document.querySelector('#side-preview-title').textContent==='Nuovo titolo di prova'`));
 await click('[data-action="navigate"][data-view="media"]');
 assert('Unsaved navigation guard',await evaluate(`document.querySelector('#dialog').open && state.dialog==='leave'`));
 await click('[data-action="close-dialog"]');
 await evaluate(`document.querySelector('#scenario').value='error'; save()`);
 assert('Error preserves draft',await evaluate(`state.error==='error' && page().title.it==='Nuovo titolo di prova' && dirty()`));
 await evaluate(`save()`);
 assert('Retry succeeds',await evaluate(`!dirty() && state.saved.pages[0].title.it==='Nuovo titolo di prova'`));
 await click('[data-action="edit-feature"][data-id="f1"]');await input('#child-title','Titolo servizio temporaneo');
 await click('[data-action="close-dialog"]');
 assert('Nested unsaved guard',await evaluate(`document.querySelector('#dialog').open && !!document.querySelector('#child-discard-warning')`));
 await click('[data-action="apply-feature"]');
 assert('Child changes staged until parent save',await evaluate(`page().features[0].title==='Titolo servizio temporaneo' && state.saved.pages[0].features[0].title==='Strategia e identità' && dirty()`));
 await click('[data-action="move-feature"][data-id="f1"][data-direction="1"]');
 assert('Reorder is staged',await evaluate(`page().features[1].id==='f1' && state.saved.pages[0].features[0].id==='f1'`));
 await click('[data-action="media-picker"]');await click('[data-action="select-media"][data-id="m2"]');await click('[data-action="close-dialog"]');
 assert('Cancel media selection preserves cover',await evaluate(`page().image==='m1'`));
 await click('[data-action="media-picker"]');await click('[data-action="select-media"][data-id="m2"]');await click('[data-action="apply-media"]');
 assert('Confirm cover stages change',await evaluate(`page().image==='m2' && dirty()`));
 await evaluate(`document.querySelector('#scenario').value='conflict';save()`);
 assert('Conflict preserves draft and shows comparison',await evaluate(`state.error==='conflict' && state.dialog==='conflict' && page().image==='m2'`));
 await click('[data-action="close-dialog"]');await evaluate(`document.querySelector('#scenario').value='session';save()`);
 assert('Session expiry preserves draft',await evaluate(`state.dialog==='session' && dirty()`));
 await click('[data-action="reconnect"]');await new Promise(r=>setTimeout(r,1100));
 assert('Reconnect and save complete',await evaluate(`!dirty() && !document.querySelector('#dialog').open`));
 await click('[data-action="navigate"][data-view="settings"]');await click('[data-setting-lang="en"]');
 assert('Disabling a language preserves translations',await evaluate(`!state.draft.langs.includes('en') && state.draft.pages[0].title.en==='Ideas take shape.'`));
 await click('[data-action="discard"]');await click('[data-action="confirm-discard"]');
 await click('[data-action="navigate"][data-view="structure"]');await click('[data-action="edit-field"][data-id="title"]');await input('#field-label','Titolo migliorato');await click('[data-action="apply-field"]');
 assert('Schema label changes without renaming key',await evaluate(`state.draft.schema[0].label==='Titolo migliorato' && state.draft.schema[0].name==='title'`));
 await evaluate(`save()`);
 await click('[data-action="navigate"][data-view="contents"]');await input('#content-search','zzznothing');
 assert('Empty search gives recovery action',await evaluate(`!!document.querySelector('[data-action="clear-search"]')`));await click('[data-action="clear-search"]');
 await click('[data-action="new-page"]');await input('#new-page-label','Contatti');await click('[data-action="create-page"]');
 assert('Create only staged before save',await evaluate(`state.draft.pages.length===3 && state.saved.pages.length===2`));
 await input('#page-title','');await evaluate(`save()`);
 assert('Validation keeps other values and focuses title',await evaluate(`state.error==='validation' && document.activeElement.id==='page-title' && state.saved.pages.length===2`));
 await click('[data-action="discard"]');await click('[data-action="confirm-discard"]');
 await evaluate(`state.draft=clone(initial);state.saved=clone(initial);state.selectedId='home';state.lang='it';state.view='edit';state.error=null;state.invalid=false;state.lastSaved=null;document.querySelector('#toasts').replaceChildren();render()`);
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 assert('Mobile has no horizontal overflow',await evaluate(`document.documentElement.scrollWidth<=390`));
 screenshot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(folder+'/anteprima-mobile.png',Buffer.from(screenshot.data,'base64'));
 await click('[data-action="media-picker"]');
 assert('Mobile dialog stays within viewport',await evaluate(`(()=>{const r=document.querySelector('#dialog').getBoundingClientRect();return r.left>=0 && r.right<=390 && r.height<=844})()`));
 await click('[data-action="close-dialog"]');
 assert('No browser runtime exceptions',exceptions.length===0);
 fs.writeFileSync(folder+'/verifica-prototipo.json',JSON.stringify({browser:'Chrome headless',results,exceptions},null,2));
 console.log(JSON.stringify({passed:results.length,results,exceptions},null,2));ws.close();
}
main().catch(e=>{console.error(e);process.exitCode=1;setTimeout(()=>process.exit(1),50);});
